#!/bin/bash

set -eo pipefail

usage() {
  echo "usage: uninstall-connector"
  echo
}

main() {
    while [[ $# -gt 0 ]]; do
      case $1 in
          -h | --help )           usage
                                  exit
                                  ;;
          * )                     ;;
      esac
      shift
  done

  declare installPath;
  installPath="$HOME/.local/share/applications"

  echo "Uninstalling Open Roberta Connector"
  rm "$installPath/ORCON.desktop"
  echo "Successfully uninstalled Open Roberta Connector"
}

main "$@"
